<a href="https://colab.research.google.com/github/salomemoram/Analitica-de-negocios/blob/main/Caso_estudio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Caso de estudio**

En este documento se desarrolla y analiza un modelo naives bayes para la preaprobacion de creditos en una entidad financiera utilizando las variables socioeconomicas de un solicitante de credito. De acuerdo con lo anterior las variables socio economicas son:

**Edad:** es la edad que posee el solicitante a la hora de solicitar un credito

**Ingresos:** Ingresos recibidos por una persona como resultado de una actividad comercial

**Egresos:** Gastos mensuales del solicitante

**Monto (EAD):** indica el dinero que una persona solicita a una entidad financiera como credito




In [ ]:
# Se cargan las librerias de trabajo
import numpy as np #Libreria numerica por excelencia
import pandas as pd #Libreria para la comunicacion de archivos de excel

# Librerias especificas
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix

In [ ]:
# Se cargan los datos de trabajo de la base de datos  Base AAA
nx1='/content/1. SolicitantesCrédito(USD) (1).xlsx'
XDB=pd.read_excel(nx1, sheet_name=1)
XDB.head(100) # Es para mostrar la base de datos

# Seleccionamos las variables de trabajo
XD=XDB[['Edad', 'Ingresos', 'Egresos', 'Monto (EAD)']] #Variables de trabajo
XD.head(10)
yd=XDB[['PreApr']] #Variable de decision
yd.head()

,PreApr
0,1
1,1
2,0
3,1
4,1


In [ ]:
# Implementamos modelo naive bayes
mnb=GaussianNB()
mnb.fit(XD, yd) #Ajustar variables entrada - salida

#Mostramos las medias de las variable
u=mnb.theta_
sigma=mnb.var_;sigma=np.sqrt(sigma)
print('Edad', 'Ingresos', 'Egresos', 'Monto (EAD)')
print(u)
print('Las desviaciones estandar son: ')
print(sigma)

Edad Ingresos Egresos Monto (EAD)
[[  40.98411626  431.42680644  401.54995644  289.41445941]
 [  41.10752688 1029.98947251  900.19312144  781.2021157 ]]
Las desviaciones estandar son: 
[[ 12.21303268 325.79791497 342.77286087 235.95783541]
 [ 12.25106493 472.43342807 525.43337837 469.90038088]]


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


**Analisis de resultados**
De los resultados arrojados por el modelo, podemos observar que la categoría de PreAprobados posee ingresos superiores a las categorías de Prellegados, esto indica claramente la predominancia de la variable para aprobar créditos. Es importante mencionar que la edad es mayor para los PreAprobados que para los prenegados, lo que indica que el banco busca personas con mayor experiencia créditicia.

Los preaprobados tiene ingresos superiores a los de la categoria prenegados, sin embargo los preaprobados estan solicitando montos superiores a los de la categoria de prenegados, esto es un indicador de la capacidad de este grupo para hacer frente a un credito.

In [ ]:
# Hacemos la evaluacion del modelo on la matriz de confusion
ydp=mnb.predict(XD) #Esto eslo que el modelo aprende de ydp de pronostico
cm=confusion_matrix(yd, ydp)
print(cm)

#se determinan las metricas de la matriz de confusion
VN=cm[0,0];FP=cm[0,1];FN=cm[1,0];VP=cm[1,1];Tdatos=len(XDB)

#1. Exactitud funcionamiento general del modelo
Ex=(VP+VN)/Tdatos
print('Exactitud: ', Ex)

#2. Tasa error porcentaje de fallos del sistema
TE=(FP+FN)/Tdatos
print('Tasa error: ', TE)


#3. Sensibilidad  como se comporto solo con los positivos
Se=VP/(VP+FN)
print('Sensibilidad:', Se)

#4. Especificidad como se comporto solo con los negativos
Es=VN/(VN+FP)
print('Especificidad:', Es)

#5. Precision es una versionde como se comporta frente a los positivos solamente
Pr=VP/(VP+FP)
print('Precision:', Pr)

#

[[2502  457]
 [ 937 1946]]
Exactitud:  0.7613830879835672
Tasa error:  0.23861691201643273
Sensibilidad: 0.6749913284772806
Especificidad: 0.8455559310577898
Precision: 0.8098210570120683


**Analisis de resultados**
De acuerdo con los resultados, podemos observar de manera general que el modelo alcanzó una exactitud por encima del 75% en promedio, lo indica el buen comportamiento del modleo frente a la clasificación de los solicitantes de crédito frente a la PreApr y la PreNegación. Se destaca la Precisión con un 88. 9%, lo que indica el buen funcionamiento del nodelo frente a la preaprobación de créditos. Igualmente, se puede observar el buen comportamiento dle nodelo frente a la prenegación de créditos, tal y como lo demuestra el indice de especificidad del nodelo, el cual estubo por encima del 84% en promedio.

In [ ]:
# Evaluamos un solicitante
xp=[34, 1500, 800, 1000]
ydc=mnb.predict([xp])
print(ydc)

if ydc==1;
print('El solicitante es PreAprobado')
else
print('El solicitante es PreNegado')

SyntaxError: invalid syntax (ipython-input-1841702611.py, line 6)